version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.20
    environment:
        MYSQL_ROOT_PASSWORD: rahasia
    ports: 
        - 3306:3306
    volumes: 
        - data:/var/lib/mysql

volumes: 
    data: