version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.3
    environment:
        POSTGRES_PASSWORD: rahasia
    ports: 
        - 5432:5432
    volumes: 
        - data:/var/lib/postgresql/data

volumes: 
    data: